name: spe_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.1.0
  dio: ^5.9.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_sign_in: ^6.2.2
  flutter_svg: ^2.2.3
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  http: ^1.6.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  location: ^8.0.1
  # flutter_riverpod already pulls in riverpod
  uuid: ^4.5.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
